run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Bugs & Errors
    - errcheck        # Detecta erros não tratados
    - govet           # Reporta construções suspeitas
    - staticcheck     # Análise estática avançada
    - unused          # Detecta código não utilizado
    - bodyclose       # Verifica se HTTP response body foi fechado
    - nilerr          # Detecta retorno de nil quando err != nil

    # Code Smells
    - gocritic        # Detecta code smells e bugs (similar ao Detekt)
    - revive          # Linter rápido e extensível (substituto do golint)
    - unconvert       # Remove conversões desnecessárias
    - unparam         # Detecta parâmetros não utilizados
    - wastedassign    # Detecta atribuições não utilizadas

    # Complexity (como Detekt)
    - gocognit        # Complexidade cognitiva (threshold: 30)
    - gocyclo         # Complexidade ciclomática (threshold: 15)
    - funlen          # Tamanho de funções (lines: 80, statements: 50)
    - nestif          # Detecta if's muito aninhados

    # Style
    - gofmt           # Verifica formatação
    - goimports       # Verifica imports
    - misspell        # Detecta erros de ortografia em comentários
    - whitespace      # Detecta whitespace desnecessário

    # Performance
    - ineffassign     # Detecta atribuições ineficientes

    # Security (como Detekt security rules)
    - gosec           # Detecta problemas de segurança

linters-settings:
  # Complexidade cognitiva (similar ao CognitiveComplexity do Detekt)
  gocognit:
    min-complexity: 30

  # Complexidade ciclomática (similar ao CyclomaticComplexMethod do Detekt)
  gocyclo:
    min-complexity: 15

  # Tamanho de funções (similar ao LongMethod do Detekt)
  funlen:
    lines: 80
    statements: 50

  # Aninhamento de if's (similar ao NestedBlockDepth do Detekt)
  nestif:
    min-complexity: 5

  # Gocritic - várias verificações de code smells
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
      - hugeParam
      - paramTypeCombine    # Estilo de assinatura de função
      - commentedOutCode    # Código comentado pode ser intencional
      - ifElseChain         # Permite if-else chains
      - rangeValCopy        # Pode ser necessário copiar valores

  # Revive - regras de estilo
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  # Gosec - regras de segurança
  gosec:
    excludes:
      - G104

  # Misspell - correção de ortografia
  misspell:
    locale: US

  # Goimports - organização de imports
  goimports:
    local-prefixes: cactus-golang-hexagonal-microservice-boilerplate

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 5

  exclude-rules:
    # Testes podem ter funções longas
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo
        - errcheck

    # Arquivos de configuração/DI podem ser longos
    - path: adapter/dependency/
      linters:
        - funlen

    # Testcontainers são longos por natureza
    - path: testcontainer
      linters:
        - funlen

    # Erros não tratados em defer são comuns
    - source: "defer"
      linters:
        - errcheck

    # Arquivos AMQP com defer/cleanup
    - path: adapter/amqp/
      linters:
        - errcheck

    # Util clean_arch tem lógica complexa
    - path: util/clean_arch/
      linters:
        - gocognit

    # Gosec warnings aceitáveis
    - linters:
        - gosec
      text: "G112|G115|G109|G306"

    # Complexidade alta em funções de configuração é aceitável
    - path: config/config\.go
      linters:
        - gocyclo

    # Funções longas em metrics e event bus são aceitáveis
    - path: util/metrics/metrics\.go
      linters:
        - funlen

    - path: domain/event/async_event_bus\.go
      linters:
        - gocognit

    # Complexidade em main.go é aceitável
    - path: cmd/main\.go
      linters:
        - gocognit
        - gocyclo
        - funlen
        - nestif

    # Complexidade em request_logger é aceitável
    - path: api/http/middleware/request_logger\.go
      linters:
        - gocognit
        - gocyclo
        - funlen

    # Complexidade em validator é aceitável
    - path: api/http/validator/validator\.go
      linters:
        - nestif

    # Complexidade em transaction é aceitável
    - path: adapter/repository/transaction\.go
      linters:
        - nestif

    # Clean arch tem lógica complexa
    - path: util/clean_arch/
      linters:
        - gocyclo

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
